### Send POST request with json body
POST http://localhost:8080/create-developers
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYear": 3,
  "memberId": "9717984",
  "name": "dolmac",
  "age": 27
}