### Send POST request with json body
POST https://localhost:8080/create-developers
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 2,
  "MemberId": "9717984",
  "name": "dolmac",
  "age": 27
}